version: '3'
services:
  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    container_name: client
    volumes:
      - ./packages/client:/app
      - /app/node_modules
