version: '3.9'
services:
  factoriaction-client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    container_name: client
    volumes:
      - type: bind
        source: ./packages/client/src
        target: /app/src